..\bin\sendtosaber.exe -s -t sON=DR_ON01.RAW
..\bin\sendtosaber.exe -s -t sOFF=DR_OFF01.RAW
..\bin\sendtosaber.exe -s -t sHUM=DR_HUM01.RAW
..\bin\sendtosaber.exe -s -t sSW=DR_SWING01.RAW,DR_SWING02.RAW,DR_SWING03.RAW,DR_SWING04.RAW,DR_SWING05.RAW,DR_SWING06.RAW,DR_SWING07.RAW,DR_SWING08.RAW,DR_SWING09.RAW
..\bin\sendtosaber.exe -s -t sCL=DR_CLASH01.RAW,DR_CLASH02.RAW,DR_CLASH03.RAW,DR_CLASH04.RAW,DR_CLASH05.RAW,DR_CLASH06.RAW,DR_CLASH07.RAW,DR_CLASH08.RAW,DR_CLASH09.RAW,DR_CLASH10.RAW,DR_CLASH11.RAW,DR_CLASH12.RAW,DR_CLASH13.RAW,DR_CLASH14.RAW
..\bin\sendtosaber.exe -s -t sSMA=
..\bin\sendtosaber.exe -t sSMB=
