..\bin\sendtosaber.exe -s -t sON=GB_ON01.RAW
..\bin\sendtosaber.exe -s -t sOFF=GB_OFF01.RAW
..\bin\sendtosaber.exe -s -t sHUM=HUM_0.RAW
..\bin\sendtosaber.exe -s -t sSW=GB_SWING01.RAW,GB_SWING02.RAW,GB_SWING03.RAW,GB_SWING04.RAW,GB_SWING05.RAW,GB_SWING06.RAW,GB_SWING.RAW,GB_SWING07.RAW,GB_SWING08.RAW,GB_SWING09.RAW,GB_SWING10.RAW,GB_SWING11.RAW,GB_SWING12.RAW,GB_SWING13.RAW
..\bin\sendtosaber.exe -s -t sCL=GB_CLASH01.RAW,GB_CLASH02.RAW,GB_CLASH03.RAW,GB_CLASH04.RAW,GB_CLASH05.RAW,GB_CLASH06.RAW,GB_CLASH07.RAW,GB_CLASH08.RAW,GB_CLASH09.RAW,GB_CLASH10.RAW,GB_CLASH11.RAW,GB_CLASH12.RAW,GB_CLASH13.RAW,GB_CLASH14.RAW,GB_CLASH15.RAW,GB_CLASH16.RAW,GB_CLASH17.RAW,GB_CLASH18.RAW
..\bin\sendtosaber.exe -s -t sSMA=
..\bin\sendtosaber.exe -s -t sSMB=
